[project]
name = "pyspecification"
version = "0.1.4"
description = "A lightweight, typed Python library for composing business rules as reusable, executable predicates."
readme = "README.md"
authors = [{ name = "aaltatan", email = "a.altatan@gmail.com" }]
requires-python = ">=3.12"
dependencies = ["pydantic==2.5.3"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
]

[project.scripts]
pyspecification = "pyspecification:main"

[project.urls]
"Homepage" = "https://github.com/aaltatan/pyspecification"
"Issues" = "https://github.com/aaltatan/pyspecification/issues"

[build-system]
requires = ["uv_build>=0.11.19,<0.12.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "devtools>=0.12.2",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "sqlalchemy>=2.0.52",
]
